name: Format

on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: npm install
        run: |
          npm install
      - name: format code
        run: |
          npm run format
      - name: push formatted code
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add --all
          git diff-index --quiet HEAD || git commit -m "Format Python Codes"
          git pull
          git push
